version: '1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: user
      POSTGRES_DB: api
  db-test:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: pass321
      POSTGRES_USER: user-test
      POSTGRES_DB: api-test
